[project]
name = "llm-zoomcamp-code"
version = "0.1.0"
description = "Notebooks and homework for the DataTalksClub LLM Zoomcamp (2026 cohort)"
readme = "README.md"
authors = [
    { name = "Alex Huaracha", email = "129701149+Alex-Huaracha@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "jupyter>=1.1.1",
    "minsearch>=0.2.0",
    "openai>=3.14.1",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
    "sqlitesearch>=0.3.0",
]
